version: '3.1'

services:

  mongodb:
    image: mongo:3.6.7
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  premierLeagueApi:
    image: premier-league-api:1.0
    container_name: "premierLeagueApi"
    ports:
      - 9000:9000
    environment:
      - MONGO_HOST=mongodb
      - APPLICATION_SECRET=${APPLICATION_SECRET:-YG:H_ITIOb;boe=>KGvsHAsx=^qxJtx_c2CdKcd/A66@jw0/0l_5XGsDgpaAhe7}
    depends_on:
      - mongodb
